# Generated by Django 3.2.13 on 2022-05-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220523_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='dropdown',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex/Parody')], default='SOME STRING', max_length=1),
        ),
    ]
