# Generated by Django 3.2.13 on 2022-05-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact_dropdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='dropdown',
            field=models.CharField(choices=[('Mumbai-Delhi', 'Mumbai-Delhi '), ('Mumbai-Chennai', 'Mumbai-Chennai'), ('Chennai-Kolkata', 'Chennai-Kolkata')], default='SOME STRING', max_length=15),
        ),
    ]
